databaseChangeLog:
  - changeSet:
      id: 1
      author: dan
      changes:
        - createTable:
            tableName: customer
            columns:
              - column:
                  name: uuid
                  type: uuid
                  constraints:
                    primaryKey: true
                    nullable: false
                    unique: true
              - column:
                  name: firstname
                  type: varchar(255)
                  constraints:
                    nullable: true
              - column:
                  name: lastname
                  type: varchar(255)
                  constraints:
                    nullable: true
              - column:
                  name: email
                  type: varchar(255)
                  constraints:
                    nullable: true