server:
    port: 12378
    contextPath: /trip

#spring:
#    datasource:
#        url: jdbc:postgresql://localhost:5432/my-bank-db
#        username: my-bank-user
#        password: my-bank-pwd
#        driver-class-name: org.postgresql.Driver